# Notebook to check how each code block work in details
# If something wrong or not working in this notebook,feel free to reach me out   email - mrkyawswarthant@outlook.com

In [3]:
# Before we begin, let's load the libraries.
%pylab notebook
import numpy as np
import numpy.linalg as la

Populating the interactive namespace from numpy and matplotlib


#### I copy this from assignment for visual
$$ L = \begin{bmatrix}
L_{A→A} & L_{B→A} & L_{C→A} & L_{D→A} & L_{E→A} & L_{F→A} \\
L_{A→B} & L_{B→B} & L_{C→B} & L_{D→B} & L_{E→B} & L_{F→B} \\
L_{A→C} & L_{B→C} & L_{C→C} & L_{D→C} & L_{E→C} & L_{F→C} \\
L_{A→D} & L_{B→D} & L_{C→D} & L_{D→D} & L_{E→D} & L_{F→D} \\
L_{A→E} & L_{B→E} & L_{C→E} & L_{D→E} & L_{E→E} & L_{F→E} \\
L_{A→F} & L_{B→F} & L_{C→F} & L_{D→F} & L_{E→F} & L_{F→F} \\
\end{bmatrix}
$$

In [4]:
# This is the matrix L which represents the probability of pats leaving from one website to another through the providing link

L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
                     [1/3, 0,   0,   0, 1/2, 0 ],
                    [1/3, 1/2, 0,   1, 0,   1/2 ],
                    [1/3, 0,   1/3, 0, 1/2, 1/2 ],
                    [0,   0,   0,   0, 0,   0 ],
                   [0,   0,   1/3, 0, 0,   0 ]])

# when we add up each column (column wise) we get total 1 for each column because our matrix L is made for probability

L.ndim # 2 dimension
L.shape # (6,6) square-matrix # we will use this shape() in later

(6, 6)

In [5]:
# We represent the number of Pats on each website with the vector (r)
# I use my own variable name for intuition which is different from our assignment 

import numpy.linalg as la # library for linear algebra operation we already called this in above
eigen_value, eigen_vector = la.eig(L) # we use eig() function to get eigen value and eigen vector from our matrix L


# deindent with crtl+/ for check
print (eigen_value) # compare with what happen after order
# print (eigen_vector) # compare with what happen after order

[ 1.        +0.j          0.31416979+0.j         -0.54288045+0.30393757j
 -0.54288045-0.30393757j -0.2284089 +0.j          0.        +0.j        ]


In [6]:
order  = np.absolute(eigen_value).argsort()[::-1]
print (order)

[0 3 2 1 4 5]


In [7]:
eigen_value = eigen_value[order]
eigen_vector = eigen_vector[:,order]

print (eigen_value)
#print (eigen_vector)

[ 1.        +0.j         -0.54288045-0.30393757j -0.54288045+0.30393757j
  0.31416979+0.j         -0.2284089 +0.j          0.        +0.j        ]


### 

In [8]:
r = eigen_vector[:,0]  # we set r be the principal eigenvector
print (r) # This r is for all columns in the matrix L 

[0.30769231+0.j 0.1025641 +0.j 0.76923077+0.j 0.48717949+0.j
 0.        +0.j 0.25641026+0.j]


### (r) is the rank array of each column in matrix L and (r) array stores the rank of all webpages (mention in video)
### To calculate the rank of each column in matrix L we need to know 3 things about all other columns in the matrix L (mention in video)
### 3 things what we need to know is -
###             - What is the rank of each columns in matrix L
###             - Are these columns (others) linked to the column (we want to know ) -- in video it is rank A
###             - How many outgoing links do we have in total?

In [9]:
# What we do is matrix multiplication of r and L which gives us updated value for r
# r is now eigen vector of matrix L
# so if we want to multiply r by L many time we can recall the initution about diagonalization 
r = L @ r # This process is iteratively until r value stop changing

#### we need automate for this iterative process until r value stop changing

In [14]:
r = 100 * np.ones(L.shape[0]) / L.shape[0]   # L.shape[0] is the total number of entries contained in L matrix
                                                                     # L.shape[0] = 6
for i in np.arange(100): # Repeat 100 times
    r = L @ r
print ("This is the final value of (r) after 100 times iteration >>> ",r) # we can try with any iteration value we want

This is the final value of (r) after 100 times iteration >>>  [16.          5.33333333 40.         25.33333333  0.         13.33333333]


In [13]:
print(np.ones(5)) # example code for np.ones() output
print (np.ones(5)/5) # example code for np.ones() output

[1. 1. 1. 1. 1.]
[0.2 0.2 0.2 0.2 0.2]


### Better solution down there

In [15]:
r = 100 * np.ones(L.shape[0]) / L.shape[0]

updated_r = r                                    # we created new variable named updated_r (copy of r) for initialization of iteration
r = L @ r

i = 0                                                   # for total count of iterations
while la.norm(updated_r - r) > 0.01: # this means when substracted value is no longer greater than 0.01 , the r value stop changing over iteration
    updated_r = r # iteration start
    r = L @ r
    i += 1
print (str(i) + " iterations to convergence")
r

18 iterations to convergence


array([16.00149917,  5.33252025, 39.99916911, 25.3324738 ,  0.        ,
       13.33433767])

In [16]:
# So I hope this comments will explain well enough if u are slow learner like me 
# Have a nice day !

# Graded Function

In [ ]:
# GRADED FUNCTION

# Complete this function to provide the PageRank for an arbitrarily sized internet.
# I.e. the principal eigenvector of the damped system, using the power iteration method.
# (Normalisation doesn't matter here)
# The functions inputs are the linkMatrix, and d the damping parameter - as defined in this worksheet.
# (The damping parameter, d, will be set by the function - no need to set this yourself.)

def pageRank(linkMatrix, d) :
    n = linkMatrix.shape[0]                                         # this is explained in example codes above we use shape for incoming Matrix entries
    M = (d * linkMatrix) + ((1-d) /n * np.ones([n, n]) )
    r = 100 * np.ones(n) / n
    lastR = r
    r = M @ r
    i = 0
    while la.norm(lastR - r) > 0.01 :
        lastR = r
        r = M @ r
        i += 1
    return r