# Diagonalisation and applications

### Sometimes we need to apply same matrix multiplication many times
### Imagine we need to make transformation of vector $ v $ by multiplying with $matrix T$ (Transformation Matrix).
### If we need to do that transformation many times $ n $ ???

### example >>> $ v_{1} = T \cdot v_{0} $
###                        $ v_{2} = T \cdot v_{1} $  that is the same for  $ v_{2} = T^{2} \cdot v_{0} $
### $ v_{n} = T^{n} \cdot v_{0} $

In [3]:
import numpy.linalg as lg

### The intuition here is diagonalization of transformation matrix make a lot of easier for computation.
### Example code down here



# Note
### Each columns of our transform matrix ( T ) simply represents the new location of the transformed unit (v)
### The Diagonal matrix  ( D ) contains the corresponding eigen values of matrix T

###                 $ D = C^{-1} T C $
###                 $ D^{2} = C^{-1} T C \cdot C ^{-1} T C $  C inverse dot with C is same as I
### Equation $ D^{n} = C^{-1} T^{n} C $

In [4]:
# Example why diagonalization makes computation easier

import numpy.linalg as lg
import numpy as np

A = np.array([[1,2],[1,2]])
print ("A >>> \n", A)
print ("A power 3 >>> \n", A**3)

print ()

B = np.array([[2,0],[0,2]])
print("B >>> \n", B)
print ("B power 3 >>> \n",B**3)

A >>> 
 [[1 2]
 [1 2]]
A power 3 >>> 
 [[1 8]
 [1 8]]

B >>> 
 [[2 0]
 [0 2]]
B power 3 >>> 
 [[8 0]
 [0 8]]


In [5]:
T = np.array([[6,-1],[2,3]])
C = np.array([[1,1],[1,2]])

In [6]:
D = lg.inv(C) @ T @ C

In [7]:
print (D)

[[5. 0.]
 [0. 4.]]


In [8]:
# Question 2
T = np.array([[2,7],[0,-1]])
C = np.array([[7,1],[-3,0]])
print (T)
print (C)
A = lg.inv(C) @ T @ C
print (A)

[[ 2  7]
 [ 0 -1]]
[[ 7  1]
 [-3  0]]
[[-1.00000000e+00  0.00000000e+00]
 [ 1.77635684e-15  2.00000000e+00]]


In [9]:
# Question 3
T = np.array([[1,0],[2,-1]])
C = np.array([[1,0],[1,1]])
print (T)
print (C)
A = lg.inv(C) @ T @ C
print (A)

[[ 1  0]
 [ 2 -1]]
[[1 0]
 [1 1]]
[[ 1.  0.]
 [ 0. -1.]]


In [10]:
# Question 4
a = 1 # Suppose 
D = np.array([[a,0],[0,a]])
C = np.array([[1,2],[0,1]])
print (D)
print (C)
T = C @ D @ lg.inv(C)
print (T)

[[1 0]
 [0 1]]
[[1 2]
 [0 1]]
[[1. 0.]
 [0. 1.]]


In [11]:
# Question 5
T = np.array([[6,-1],[2,3]])
diagonal_D = np.array([[5,0],[0,4]])
C = np.array ([[1,1],[1,2]])

T_Pow_3 = C @ diagonal_D**3 @ lg.inv(C)
T_Pow_3

array([[186., -61.],
       [122.,   3.]])

In [12]:
# Question 6
T = np.array([[2,7],[0,-1]])
diagonal_D = np.array([[-1,0],[0,2]])
C = np.array([[7,1],[-3,0]])

T_pow_3 = C @ diagonal_D ** 3 @ lg.inv(C)

T_pow_3

array([[ 8., 21.],
       [ 0., -1.]])

In [13]:
# Question 7
T = np.array([[1,0],[2,-1]])
C = np.array([[1,0],[1,1]])
D = np.array([[1,0],[0,-1]])

T_power_5 = C @ D ** 5 @ lg.inv(C) # Same as formula whatever the power for transformation matrix we need the same power apply to diagonal matrix
T_power_5

array([[ 1.,  0.],
       [ 2., -1.]])

In [14]:
# U can stimulate in geometrical space in next exercise ! Have a nice day

In [15]:
A = np.array([[1,1],[2,2]])

I = np.array([[1,0],[0,1]])

In [16]:
A @ I

array([[1, 1],
       [2, 2]])

 https://www.coursera.org/learn/linear-algebra-machine-learning/ungradedWidget/AVEfF/visualising-matrices-and-eigen

In [17]:
lg.det(A)

0.0

In [18]:
lg.inv(A) # Error because  A has no inverse because determinant = 0

LinAlgError: Singular matrix

In [ ]:
import numpy.linalg as lg
import numpy as np

S = np.array([[3,0],[1,1]])

In [ ]:
lg.det(S)  # S has determinant

In [ ]:
lg.inv(S) # S has inverse

In [54]:
T = S @ lg.inv(S)

NameError: name 'S' is not defined

In [55]:
T # T = I

array([[ 1,  0],
       [ 2, -1]])